name: Simplified Module CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs: 
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Setup Node.js environment
    - uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    # Install dependencies and run build script
    - run: npm install
    - run: npm run build

    # Zip the contents of the dist directory
    - name: Zip dist directory
      run: |
        cd dist
        zip -r ../module.zip .
        cd ..

    # Extract version for release
    - name: Extract version for release
      run: echo "RELEASE_VERSION=$(node -p "require('./src/module.json').version")" >> $GITHUB_ENV
  
    # Create Release
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        files: |
          module.zip
          dist/module.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
